// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gganwremavfeuxndtueu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnYW53cmVtYXZmZXV4bmR0dWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0ODA2MjUsImV4cCI6MjA1NjA1NjYyNX0.R_imFTwsbTIoptGdJ_vO0hL8Q3CRSFFKtvzxex9-840";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);